### ISSUE TITLE
Project Future

### ISSUE THREAD

**Issue by ghost** [nbriz/threejs_playGnd#15]
@nbriz  you mentioned in a previous issue that you wanted to update this project. 
Would you be able to add to the readme showing how to setup a local hosting of the project.
If you do this as a starting point, I would love to fork the project and continue development!

**Comment by nbriz** [comment]
hey @harryiliffe glad u're interested in helping bring this back to life! so it's been a while since i worked on this code base, but if memory serves me right it's all statically hosted. i think we're running a pretty basic LAMP setup. The only part that isn't static is the archive page (which is php, as it communicates w/the SQL database where we've stored the sketches). just to confirm that was the case, i just flipped on "github pages" on this repo to see if it would work && voilà: http://nbriz.github.io/threejs_playGnd/

that said, like u mentioned, i have been wanting to update this. in large part due to the fact that the library has changed quite a bit since the version we're using on the playGnd. i've also learned A LOT more about putting together code playground's like this since then (this was my first one). so rather than working on this code base my plan is to create an entirely new play ground. while i realize this sounds ambitious, i've actually already started working on such a play ground via my not for profit https://github.com/netizenorg/ (u can check out the first draft of the editor component for the new play ground here https://github.com/netizenorg/netitor) this new playground isn't going to be simply for threejs, rather it will focus on various web APIs && libraries of interest to artist && creative coders.

all this just to say, if u're interested on helping bring this back to life it be more advantageous to get ur help on our new playground rather than this old one... but, all of this is open source, so u are of course free to fork this old repo && remix to ur hearts content :)

**Comment by ghost** [comment]
Hey @nbriz Thank you so much for this quick but thoray response.
I have checked out netitor editor and it looks amazing. 
I would love to participate in the development and will keep an eye on your progress!
